# Generated by Django 3.2.3 on 2021-06-10 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='reporting_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('hired', 'Hired')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
