# Generated by Django 3.2.4 on 2021-07-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210702_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
