# Generated by Django 3.2.4 on 2021-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210721_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
